GPI/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get '/LAUDUS', to: 'materials#show'

  get '/cotizaciones', to: 'cotizaciones#show'
  
  get '/crearoc', to: 'ordencompras#new'
  post '/crearoc', to: 'ordencompras#create'

  get '/users/:id', to: 'users#show'

  get '/newmaterial', to: 'materials#new'
  post '/newmaterial', to: 'materials#create'

  get 'welcome/index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'  
  
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :ordencompras
  resources :materials
  
  root 'welcome#index'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

GPI/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GPI/app/models/material.rb
class Material < ApplicationRecord
  belongs_to :ordencompra
end

GPI/app/models/ordencompra.rb
class Ordencompra < ApplicationRecord
	has_many :materials, dependent: :destroy
	accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: lambda {|attributes| attributes['material'].blank?}
end

GPI/app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

GPI/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

GPI/app/controllers/cotizaciones_controller.rb
class CotizacionesController < ApplicationController
  def index
  end

  def show
  	l = JSON.parse('{
  "materiales": [
    { "id": 1, "vendedor": "proveedor1", "material": "manguera", "cantidad": 3, "precio": 5000 },
    { "id": 2, "vendedor": "proveedor2", "material": "clavo", "cantidad": 100, "precio": 1500 },
    { "id": 3, "vendedor": "proveedor3", "material": "ampolleta", "cantidad": 20, "precio": 6200 }
  ]
}')
    render json: l, status: :created, location: @cotizacion
  end
end

GPI/app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
	def new
		@material = Material.new
	end

	def create
      @material = Material.new(material_params)
      if @material.save
        flash[:success] = "Orden de compra generada con éxito!"
        redirect_to user_path(session[:user_id])
      else
        render 'new'
      end
    end

    def show
    end

    private

  def material_params
    params.require(:material).permit(:material, :cantidad)
  end

end

GPI/app/controllers/ordencompras_controller.rb
class OrdencomprasController < ApplicationController
	def show
    	@ordencompra = Ordencompra.find(params[:id])
  	end

	def new
		@ordencompra = Ordencompra.new
    2.times { @ordencompra.materials.build }
	end

	def create
      @ordencompra = Ordencompra.new(oc_params)
      if @ordencompra.save
        render json: oc_params, status: :created, location: @ordencompra
        flash[:success] = "Orden de compra generada con éxito!"
        #redirect_to user_path(session[:user_id])
      else
        render 'new'
      end
    end

    private

  def oc_params
    params.require(:ordencompra).permit(:comprador, materials_attributes: [:id, :material, :cantidad, :_destroy])
  end

end

GPI/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      redirect_to user
  	else
  		flash.now[:danger] = 'Email/contraseña incorrecto/s'
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

GPI/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "Usuario creado exitosamente! Inicie sesión con sus datos:"
        redirect_to login_url
      else
        render 'new'
      end
    end

    def nuevaOC
      @user = User.find(params[:id])
      render @user.name
    end

    private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :tipo)
  end

end

GPI/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

GPI/app/helpers/application_helper.rb
module ApplicationHelper
end

GPI/app/helpers/materials_helper.rb
module MaterialsHelper
end

GPI/app/helpers/ordencompras_helper.rb
module OrdencomprasHelper
end

GPI/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
		#session[:nombre] = user.name
		#session[:email] = user.email
		#session[:tipo] = user.tipo
		#session[:password] = user.password_digest 
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

GPI/app/helpers/users_helper.rb
module UsersHelper
end

GPI/app/helpers/welcome_helper.rb
module WelcomeHelper
end

GPI/app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>

      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

          <% if logged_in? %>
          <a class="navbar-brand" href=<%= user_path(session[:user_id]) %> >GPI</a>

            <li class="nav-item">
                <%= link_to "Cerrar Sesión", logout_path, method: :delete, class: "nav-link" %>
            </li>
          
          <% else %>

          <a class="navbar-brand" href=<%= root_path %> >GPI</a>

          <li class="nav-item">
              <%= link_to 'Login', login_path, class: "nav-link" %>
          </li>

          <% end %>

        </ul>
      </div>
    </header>

GPI/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GPI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= render 'layouts/header' %>
    	<div class="container">
      <%= yield %>
      </div>

      <!-- Debug info -->
    	<% if false %>
      <%= debug(params) if Rails.env.development? %>
      <% end %>

	</div>
  </body>
</html>

GPI/app/views/materials/show.html.erb
<h1>HOLA</h1>

GPI/app/views/ordencompras/new.html.erb
<% provide(:title, 'Nueva OC') %>
<h1>Generar Nueva Orden de Compra</h1>
<h2> Ingrese los datos de la orden </h2>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @ordencompra, url: {action: "create"} do |f| %>

		<div class="form-group row">
			<%= f.label :comprador, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">
			<%= f.text_field :comprador, :value => current_user.email, :readonly => true,  class: "form-control-plaintext" %>
			</div>
		</div>

		<div class="form-group row">
			<%= f.label "Materiales:", class: "col-sm-2 col-form-label" %>
			<ul>
				<%= f.fields_for :materials do |materials_form| %>
				<li>
					<%= materials_form.check_box :_destroy, class: 'form-control' %>
					<%= materials_form.label :material %>
					<%= materials_form.text_field :material, class: 'form-control' %>

					<%= materials_form.label :cantidad %>
					<%= materials_form.number_field :cantidad, :min => 1, :max => 200, class: 'form-control' %>					
				</li>
				<% end %>
			</ul>
		

			<%= f.submit "Generar", class: "btn btn-primary" %>
			</div>
		<% end %>
		<%= link_to "Volver", user_path(session[:user_id]) %>
	</div>
</div>

GPI/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Error al crear usuario: <!-- <%= pluralize(@user.errors.count, "error") %>. -->
    </div>
    <ul>

    <% @user.errors.full_messages.each do |msg| %>

      <% if msg == "Name can't be blank" %>
        <li><%= "Debe indicar su nombre" %></li>
      <% end %>
      <% if msg == "Email can't be blank" %>
        <li><%= "Debe indicar su email" %></li>
      <% end %>
      <% if msg == "Email is invalid" %>
        <li><%= "Email inválido" %></li>
      <% end %>
      <% if msg == "Password can't be blank" %>
        <li><%= "Debe indicar su contraseña" %></li>
      <% end %>
      <% if msg == "Password is too short (minimum is 6 characters)" %>
        <li><%= "La contraseña es muy corta (mínimo 6 caracteres)" %></li>
      <% end %>

    <% end %>

    </ul>
  </div>
<% end %>

GPI/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registrarse</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :tipo, "Tipo de funcionario" %>
      <%= f.select :tipo, options_for_select(["Encargado de Adquisiciones", "Encargado de Bodega Central", "Encargado de Obra", "Encargado de Bodega de Obra"]), class: 'form-control' %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirme Contraseña" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>


      <%= f.submit "Crear Usuario", class: "btn btn-primary" %>
    <% end %>
    <p>Volver a <%= link_to "Iniciar Sesión", login_path %></p>
  </div>
</div>

GPI/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        Bienvenido <%= current_user.name %>
      </h1>
      <p>
      	<%= @user.tipo %>
      </p>
      </aside>
      </section>
      </div>

      <!-- ENCARGADO DE ADQUISICIONES -->
      <% if @user.tipo == "Encargado de Adquisiciones" %>
      	<div class="row">

          <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Generar nueva orden de compra</h5>
              <p class="card-text">Crear una nueva orden de compra para subir a LAUDUS</p>
              <a href=<%= crearoc_path %> class="btn btn-primary">Generar</a>
              
            </div>
          </div>
          </div>

          <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Revisar cotizaciones</h5>
              <p class="card-text">Listado de cotizaciones recibidas de LAUDUS</p>
              <a href=<%= cotizaciones_path %> class="btn btn-primary">Generar</a>
              
            </div>
          </div>
          </div>

        </div>

        <!-- Nav tabs -->
        <!--
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="messages-tab" data-toggle="tab" href="#messages" role="tab" aria-controls="messages" aria-selected="false">Messages</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="false">Settings</a>
  </li>
</ul>

<-- Tab panes --
<div class="tab-content">
  <div class="tab-pane active" id="home" role="tabpanel" aria-labelledby="home-tab">...</div>
  <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
  <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">...</div>
  <div class="tab-pane" id="settings" role="tabpanel" aria-labelledby="settings-tab">...</div>
</div>
-->
      <% end %>
  

GPI/app/views/welcome/index.html.erb
<div class="center jumbotron">
<h1>Bienvenido!</h1>
<%= link_to 'Iniciar Sesión', login_path, class: "btn btn-lg btn-primary" %>  <%= link_to 'Registrarse', signup_path, class: "btn btn-lg btn-primary" %>
</div>